---
- name: Install Shorewall
  ansible.builtin.apt:
    pkg: shorewall,fail2ban,python-pyinotify
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify:
  - restart shorewall
  - restart fail2ban

- name: Configure
  ansible.builtin.template:
    src: "shorewall/{{ item.src }}"
    dest: "/etc/shorewall/{{ item.dest }}"
  with_items:
  - { src: interfaces.j2, dest: interfaces }
  - { src: policy.j2, dest: policy }
  - { src: rules.j2, dest: rules }
  - { src: shorewall.conf.j2, dest: shorewall.conf }
  - { src: zones.j2, dest: zones }
  register: reg_shorewall_configure

- name: Test
  ansible.builtin.command: shorewall check
  when: reg_shorewall_configure is changed
  notify: restart shorewall

- name: Configure default
  ansible.builtin.template:
    src: default/shorewall.j2
    dest: /etc/default/shorewall

- name: Enable service
  ansible.builtin.service:
    name: shorewall
    enabled: "{{ shorewall_enable }}"

- name: Configure fail2ban
  ansible.builtin.template:
    src: fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
