---
- name: Remove previous repository config
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/nginx_org_packages_debian.list
    state: absent

- name: Update APT
  ansible.builtin.apt:
    update_cache: true

- name: Add repository config trusting the expired key
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] https://nginx.org/packages/debian {{ ansible_distribution_release }} nginx"
