---
- name: Install GPG
  ansible.builtin.apt:
    pkg: gpg
    state: present
    update_cache: false

# Base path is ansible folder
- name: Add key
  ansible.builtin.apt_key:
    data: "{{ lookup('file', key_path) }}"
    state: present
