---
- name: Update exim4 config
  ansible.builtin.command: update-exim4.conf
  changed_when: true
  notify: Restart exim4

- name: Restart exim4
  ansible.builtin.service:
    name: exim4
    enabled: true
    state: restarted
