---
- name: update exim4 config
  ansible.builtin.command: update-exim4.conf
  notify: restart exim4

- name: restart exim4
  ansible.builtin.service:
    name: exim4
    enabled: yes
    state: restarted
