---
- name: Add PostgreSQL repo key
  ansible.builtin.copy:
    src: postgresql.gpg
    dest: /usr/share/keyrings/postgresql.gpg
    owner: root
    group: root
    mode: "0644"

- name: Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/postgresql.gpg] https://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Install PostgreSQL client packages
  ansible.builtin.apt:
    pkg: "{{ postgres_default_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
