---
- name: "Remove Postgres {{ version }} packages"
  ansible.builtin.apt:
    pkg: "postgresql-client-{{ version }}"
    state: absent
    purge: true
    update_cache: true
    cache_valid_time: 3600
  failed_when: false
