---
- name: Create environment files
  ansible.builtin.template:
    src: environment.j2
    dest: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ environment_files }}"
  loop_control:
    label: "{{ item.file }}"

- name: Create dotenv files
  ansible.builtin.template:
    src: dotenv.j2
    dest: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ dotenv_files }}"
  loop_control:
    label: "{{ item.file }}"
