---
- name: Add PostgreSQL repo key
  ansible.builtin.copy:
    src: postgresql.gpg
    dest: /usr/share/keyrings/postgresql.gpg
    owner: root
    group: root
    mode: "0644"

- name: Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/postgresql.gpg] https://apt.postgresql.org/pub/repos/apt/ {{ ansible_facts['distribution_release'] }}-pgdg main"
    state: present

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    pkg: "{{ postgres_default_packages + postgres_additional_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure required locale present
  community.general.locale_gen:
    name: "{{ postgres_locale }}"
    state: present

- name: Configure PostgreSQL
  ansible.builtin.template:
    src: postgresql-{{ postgres_version }}.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    mode: "0644"
  register: check_postgres_configure

- name: Set access control
  ansible.builtin.template:
    src: pg_hba-{{ postgres_version }}.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0640"
  register: check_postgres_access

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql.service
    enabled: true
    state: restarted
  when: check_postgres_configure is changed or check_postgres_access is changed

- name: Create databases
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgres_databases }}"

- name: Create users
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    db: "{{ item.db | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
  no_log: true
  with_items: "{{ postgres_users }}"

- name: Apply privs
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ item.db }}"
    roles: "{{ item.roles }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type | default(omit) }}"
    objs: "{{ item.objs | default(omit) }}"
  with_items: "{{ postgres_privs }}"

- name: Enable extensions
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: "{{ item.name }}"
    db: "{{ item.db }}"
  with_items: "{{ postgres_extensions }}"
