---
- name: restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
    enabled: yes

- name: Reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded
    enabled: yes
