---
- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
    enabled: true

- name: Reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded
    enabled: true
