---
- name: "Remove PHP packages: {{ php_remove_version }}"
  ansible.builtin.apt:
    pkg: "php{{ php_remove_version }}-*"
    state: absent
    purge: true
    update_cache: true
    cache_valid_time: 3600
  failed_when: false
