---
- name: "Remove PHP {{ php_remove_version }} packages"
  ansible.builtin.apt:
    pkg: "php{{ php_remove_version }}-*"
    state: absent
    purge: true
    update_cache: true
    cache_valid_time: 3600
  ignore_errors: true
