---
- name: Manage repo key
  ansible.builtin.import_tasks: add-key.yml

- name: Add MySQL repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/mysql-repo.gpg] https://repo.mysql.com/apt/debian/ {{ ansible_distribution_release }} mysql-{{ mysql_version }}

- name: Check if MySQL server installed
  ansible.builtin.shell: dpkg-query -W -f='${db:Status-Abbrev}' mysql-server || true
  changed_when: false
  register: mysql_installed

- name: Install MySQL server
  ansible.builtin.apt:
    pkg: mysql-server,python3-pymysql
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Stop MySQL if fresh install
  ansible.builtin.service:
    name: mysql
    state: stopped
  when: mysql_installed.stdout != "ii "

- name: Delete InnoDB logs if fresh install # changing logfile size causes restart issue until logs deleted
  ansible.builtin.shell: rm -f /var/lib/mysql/ib_logfile[01]
  when: mysql_installed.stdout != "ii "

- name: Configure
  ansible.builtin.template:
    src: tuning.cnf.j2
    dest: /etc/mysql/conf.d/tuning.cnf
    owner: root
    group: root
    mode: "0644"
  notify: Restart mysql

- name: Start MySQL if fresh install
  ansible.builtin.service:
    name: mysql
    state: started
  when: mysql_installed.stdout != "ii "

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host_all: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    plugin: caching_sha2_password
    plugin_auth_string: "{{ mysql_root_password }}"
    check_implicit_admin: true
    column_case_sensitive: true

- name: Create databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items: "{{ mysql_databases }}"

- name: Create users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    plugin: caching_sha2_password
    plugin_auth_string: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    column_case_sensitive: true
  no_log: false
  loop_control:
    label: "{{ item.name }}@{{ item.host | default('localhost') }}"
  with_items: "{{ mysql_users }}"
