---
- name: Install DO DNS plugin via apt
  ansible.builtin.apt:
    name: python3-certbot-dns-digitalocean
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution_major_version | int < 13

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution_major_version | int >= 13

- name: Install DO DNS plugin via pip
  ansible.builtin.pip:
    name: certbot-dns-digitalocean
    state: present
    extra_args: --break-system-packages
  when: ansible_distribution_major_version | int >= 13

- name: Create DO DNS credentials file
  ansible.builtin.copy:
    content: |
      dns_digitalocean_token = "{{ certbot_digitalocean_dns_token }}"
    dest: /etc/letsencrypt/digitalocean.ini
    owner: root
    group: root
    mode: "0600"

- name: Process certificates
  with_items: "{{ certbot_certs }}"
  ansible.builtin.include_tasks: dns-digitalocean-certs.yml
  loop_control:
    loop_var: certbot_certs_item
    label: "{{ certbot_certs_item.name }}"
  when: certbot_certs|length > 0
