---
- name: Install certbot
  ansible.builtin.apt:
    name: "certbot"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Running in {{ certbot_mode }} mode"
  ansible.builtin.include_tasks: "{{ certbot_mode }}.yml"
