---
- name: Install certbot
  ansible.builtin.apt:
    name: "certbot"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Include tasks for mode: {{ certbot_mode }}"
  ansible.builtin.include_tasks: "{{ certbot_mode }}.yml"
