---
- name: Remove chrome package
  ansible.builtin.apt:
    pkg: google-chrome-stable
    state: absent
  failed_when: false # there appears to be an ansible bug causing a seg fault when the package is already removed

- name: Remove google repository
  ansible.builtin.apt_repository:
    filename: google-chrome
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: absent

- name: Remove remaining config files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/google-chrome.list
    - /usr/local/bin/chromedriver-linux64
    - /usr/local/bin/LICENSE.chromedriver
