---
- name: restart shorewall
  ansible.builtin.command: shorewall restart
  when: shorewall_enable

- name: restart shorewall6
  ansible.builtin.command: shorewall6 restart
  when: shorewall_enable

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban.service
    enabled: yes
    state: restarted
