---
- name: DBCD Server
  ansible.builtin.include_tasks: server.yml
  when: "'server' in dbcd_modes"

- name: DBCD Client
  ansible.builtin.include_tasks: client.yml
  when: "'client' in dbcd_modes"

- name: DBCD Consumer
  ansible.builtin.include_tasks: consumer.yml
  when: "'consumer' in dbcd_modes"
