---
- name: Import key task
  ansible.builtin.import_tasks: add-key.yml

- name: Add Yarn repo
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb [signed-by=/usr/share/keyrings/yarn-repo.gpg] https://dl.yarnpkg.com/debian/ stable main"

- name: Install Yarn
  ansible.builtin.apt:
    pkg: yarn
    state: present
    update_cache: true
    cache_valid_time: 3600
