---
- import_tasks: add-key.yml

- name: Add Yarn repo
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb [signed-by=/usr/share/keyrings/yarn-repo.gpg] https://dl.yarnpkg.com/debian/ stable main"

- name: Install Yarn
  apt:
    pkg: yarn
    state: present
    update_cache: yes
    cache_valid_time: 3600
