---
# yamllint disable rule:line-length
- name: "Remove Node old repo: {{ node_version }}"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
    - "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_facts['distribution_release'] }} main"
    - "deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_facts['distribution_release'] }} main"
# yamllint enable rule:line-length
