---
- name: Install GnuPG
  ansible.builtin.apt:
    name: gnupg2
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Per-user GPG config
  ansible.builtin.include_tasks: per_user.yml
  with_items: "{{ gpg_config }}"
  loop_control:
    loop_var: gpg_user_config
