---
- name: Create mailhog user
  ansible.builtin.user:
    name: "{{ mailhog_user }}"
    createhome: false
    shell: /bin/false
    system: true
    password: "*"

- name: Create mailhog directory
  ansible.builtin.file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: Download mailhog binary
  ansible.builtin.get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: "0755"

- name: Install mailhog service
  ansible.builtin.template:
    src: mailhog.service.j2
    dest: /lib/systemd/system/mailhog.service
    owner: root
    group: root
    mode: "0755"

- name: Enable mailhog service
  ansible.builtin.service:
    name: mailhog.service
    enabled: true
    state: started
